{% set name = "crawl4ai" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crawl4ai-{{ version }}.tar.gz
  sha256: eb79c8930a2230df6efba18f942628f096e963799f5c66aa380b30347d895daa

build:
  entry_points:
    - crawl4ai-download-models=crawl4ai.model_loader:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - aiosqlite ==0.20.0
    - html2text ==2024.2.26
    - lxml ==5.3.0
    - litellm ==1.48.0
    - numpy >=1.26.0,<2.1.1
    - pillow ==10.4.0
    - playwright-python ==1.47.0
    - python-dotenv ==1.0.1
    - requests >=2.26.0,<2.32.3
    - beautifulsoup4 ==4.12.3

test:
  imports:
    - crawl4ai
  commands:
    - pip check
    - crawl4ai-download-models --help
  requires:
    - pip

about:
  home: https://github.com/unclecode/crawl4ai
  summary: '🔥🕷️ Crawl4AI: Open-source LLM Friendly Web Crawler & scraper'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
